### ISSUE TITLE
Decide on Release Manager 

### ISSUE THREAD

**Issue by karanrk** [airavata-courses/kr2#2]
* Must do a quick code review before merging changes to master.

**Comment by raghu2094** [comment]
Still pending. Any volunteers? @karanrk  @DGRamya

**Comment by DGRamya** [comment]
I prefer @raghu2094 :).  (after me messing up the pull request).

**Comment by karanrk** [comment]
@raghu2094  - Congratulations on your new position as "Release Manager".
