### ISSUE TITLE
Ansible Script not working

### ISSUE THREAD

**Issue by BharathaAravind** [airavata-courses/kr2#25]
Hi,
I followed the instructions mentioned in the wiki.
I am using Ubuntu 18 in an Oracle VM.
I get an error saying "The signature couldn't be verified because the public key is not available."

The manual steps to run the application is not complete.

Thanks,
Aravind.

**Comment by raghu2094** [comment]
@BharathaAravind  Hi Aravind, the issue seems to be with installation of docker for ubuntu 18. The script which we have works fine for ubuntu 16. 
Can you try installing docker by following the link : 
https://linuxize.com/post/how-to-install-and-use-docker-on-ubuntu-18-04/
Execute Steps 01- 04 from the link.

**Comment by raghu2094** [comment]
@BharathaAravind  Also I can see the error being thrown is curl command not found. Can you install curl using the following commands
$ sudo apt-get update
$ sudo apt-get install curl

**Comment by BharathaAravind** [comment]
Hi Raghu,

Installed curl and docker and tried running ansible file. I am getting the following error now.

TASK [Install docker only if docker not installed] *****************************
skipping: [localhost]

TASK [Docker - pip install] ****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "pip2 install docker", "msg": "[Errno 2] No such file or directory", "rc": 2}

Thanks,
Aravind.

**Comment by raghu2094** [comment]
@BharathaAravind I have updated the pre-requistes. You will have to install python 2.7 and pip2 as you are using a VM.

**Comment by BharathaAravind** [comment]
@raghu2094 I have used the ansible script to deploy the application on localhost. 
The installation prerequisites is missing other dependencies to. In addition python 2.7 and pip2. I had ti install python3 and Node and npm.

The tasks mentioned in ansible to install python3 and node if not found were not working.

Please update your wiki with all the prerequisites required for running ansible playbook.

Apart from the installation problems all the services are working good and I could get all the open job postings.

**Comment by raghu2094** [comment]
@BharathaAravind Can you provide the error which you faced when the step installing python3 and Node failed in the ansible script

**Comment by BharathaAravind** [comment]
@raghu2094 I haven't noted the error down. But it said python3, node and nom were not installed.
You can reproduce the error by running it on any newly installed ubuntu os or just uninstall all the softwares in your local dev machine and follow the instructions mentioned in the wiki.
