### ISSUE TITLE
Project Milestone 1 Review 

### ISSUE THREAD

**Issue by karankotz** [airavata-courses/kr2#27]
1> Followed the steps in the wiki to build the code using the ansible script in the branch CI / CD
2> The application is running fine.
3> The project architecture and division of functionalities with the micro services is good.
4> Although, you can improve the UI (pagination) and increase the search index to global job search.

**Comment by karanrk** [comment]
@karankotz - Thanks for your suggestion on pagination of the results and also we have plans to include indeed jobs that will increase the job traffic to our US Naukri system. Both of these will be added to our next milestone.

**Comment by DGRamya** [comment]
@karankotz, we will work on enhancing the UI and include that as a task for next milestone., Could you please close the issue.
