### ISSUE TITLE
Fix UI for Go microservice

### ISSUE THREAD

**Issue by karanrk** [airavata-courses/kr2#28]

**Comment by karanrk** [comment]
UI working as expected in React for Go microservice.

**Comment by raghu2094** [comment]
https://github.com/airavata-courses/kr2/commit/9e3a5a2df627c75a21d58c19eebf6900f56aff80
https://github.com/airavata-courses/kr2/commit/0f7e084a31fcb13c99f0a3d09fa5a9b64062aec8
