### ISSUE TITLE
Decide on Mongo Driver

### ISSUE THREAD

**Issue by DGRamya** [airavata-courses/kr2#3]
Which one to use for our project? MongoDB or Mongoose

MongoDB is the software that manages durable storage and efficient retrieval & processing of your data, Mongoose is a set of high-level APIs for interaction with MongoDB, using JS as a language.

Few links for analysis:
https://stackoverflow.com/questions/28712248/difference-between-mongodb-and-mongoose

https://medium.com/@bugwheels94/performance-difference-in-mongoose-vs-mongodb-60be831c69ad

**Comment by raghu2094** [comment]
As discussed and agreed upon in the meeting, we will be using pure Mongo DB
