### ISSUE TITLE
Service registration in Zookeeper

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/kr2#53]
https://github.com/apache/curator/tree/master/curator-examples/src/main/java/discovery

**Comment by raghu2094** [comment]
Service registration done

**Comment by karanrk** [comment]
commit id - 55982de8946647a320584c1d4be8ad2f44bc9e30
commit id - 0ac0c71275b7cea4683a57174d6d7a9e15189a3a 
commit id - d0eca7790d3c0024f2f7c5a8b6a24868ae289a97
