### ISSUE TITLE
Tracking Issue for Project Milestone 2 Peer Review

### ISSUE THREAD

**Issue by karankotz** [airavata-courses/kr2#56]
Will be closing the issue when the demo is completed.

**Comment by karankotz** [comment]
The Jetstream URLs mentioned in the wiki seem to run fine with the mentioned functionalities. Although I have not tested these extensively. 
One suggestion would be to highlight the use case of Kafka and Zookeeper in your project. The current UI looks good than before, although you can improvise on making the UI more user freindly. 

As discussed, please provide the credentials for the Jenkins to my email at kkotabag@iu.edu

**Comment by raghu2094** [comment]
@karankotz Hi Karan, 
Sorry the documentation was not updated, We are doing it now and let you know once done

**Comment by raghu2094** [comment]
@karankotz have mailed the Jenkins creds. Please check

**Comment by karankotz** [comment]
@raghu2094 Thanks for update, and providing the credentials, the Jenkins looks good!

**Comment by DGRamya** [comment]
@karankotz , if no issues found, can you close the issue please.
