### ISSUE TITLE
Peer Review for project 2

### ISSUE THREAD

**Issue by Keerthi4308** [airavata-courses/kr2#64]
Starting peer-review for project 2

**Comment by Keerthi4308** [comment]
Broker is down so took a quick demo from the team member for now. 
Inquired about kafka usage in terms of service

**Comment by DGRamya** [comment]
@Keerthi4308 as discussed, one of the other reviewer was running build scripts, during test. You can access the server in sometime. You can verify and close the issue

**Comment by Keerthi4308** [comment]
UI is pretty good and clean for me, team members are very responsive.
