### ISSUE TITLE
Peer Review for Milestone 3

### ISSUE THREAD

**Issue by BharathaAravind** [airavata-courses/kr2#69]
Hi Team,

Is there anyway that I can see the observations you guys made on AIRAVAT_DEV server and PIE charts made in python.

**Comment by DGRamya** [comment]
You can clone the repo, and checkout AiravataProfile, you can see the example log file, python parser tool. Once you execute you will get the PIE chart of the components. Refer README to execute

**Comment by BharathaAravind** [comment]
cloned AirvataProfile and ran the python parser tool. Got the pie charts of the components.
