### ISSUE TITLE
Integrate Pie charts to appParser tool

### ISSUE THREAD

**Issue by karanrk** [airavata-courses/kr2#76]

**Comment by DGRamya** [comment]
Used matplotlib library of python to depict the response time of each component in airavata for experiment execution

**Comment by DGRamya** [comment]
Code commits
https://github.com/airavata-courses/kr2/commit/457fd7732b71b1cf2a0e107f27f29778a4bfbe59

https://github.com/airavata-courses/kr2/commit/1ece69bd8a49efe637b99d5c10b464500d8d6678

https://github.com/airavata-courses/kr2/commit/bf77904a72e831ec482a4f254fa6ccb59204be5e
