### ISSUE TITLE
Create high level and detailed architecture diagram on draw.io

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/kr2#81]

**Comment by DGRamya** [comment]
Used draw.io to create the code control flow of apache airavata for simple experiment execution

**Comment by DGRamya** [comment]
Code commit
https://github.com/airavata-courses/kr2/commit/4d12594144b93bf68e978c0eb83c9a8dde6b5da7
https://github.com/airavata-courses/kr2/commit/90c7735e68be35c391e6c63d7b2f4be8956f45ce
https://github.com/airavata-courses/kr2/commit/342be1f7e80a2aeb04187e205134b56003ac9589
https://github.com/airavata-courses/kr2/commit/6c2c20a01c7c87c951a65590ef31120cc5b4a98f
https://github.com/airavata-courses/kr2/commit/69e0b16c15459f904a420eecca55501c1c9e74da
